spring:
  application:
    name: msgerencialprojeto
  datasource:
    url: jdbc:postgresql://dpg-co45bun79t8c738uvgqg-a.oregon-postgres.render.com:5432/locadora_ncgd
    username: locadora_ncgd_user
    password: ivXnkbz179AsDEmgWNz7jE6exKJ73mMu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


endereco:
  database: jdbc:postgresql://dpg-co45bun79t8c738uvgqg-a.oregon-postgres.render.com:5432/locadora_ncgd
  username: locadora_ncgd_user
  password: ivXnkbz179AsDEmgWNz7jE6exKJ73mMu


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    adicionar-colaborador: adicionar-colaborador
    atualizar-colaborador: atualizar-colaborador

management:
  endpoint:
    web:
      exposure:
        include: '*'

