name: Deploy do serviço ms-pmi-gerencial-projeto para Homologação

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Construir com Maven
      run: mvn -B package --file pom.xml

    - name: Listar arquivos no diretório target
      run: ls -la ./target

    - name: Construir imagem Docker
      run: docker build . -t daniel0208/gerencial-projeto-app-pmi
      working-directory: ./  # Define o contexto como o diretório raiz onde o Dockerfile está localizado

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: daniellopes0208@hotmail.com
        password: pedropaulo123

    - name: Push Docker image to Docker Hub
      run: docker push daniel0208/gerencial-projeto-app-pmi:latest
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
 #     uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
